services:

  backend:
    image: caliber001/brainbrush-backend:latest
    container_name: brainbrush-backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    environment:
      - PORT=5000

  frontend:
    image: caliber001/brainbrush-frontend:latest
    container_name: brainbrush-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend
